const $=(s,e=document)=>e.querySelector(s), $$=(s,e=document)=>[...e.querySelectorAll(s)];
const esc=s=>(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const state={notions:[],view:'house',floor:'Rez-de-chaussée',room:null,current:null,highlight:null,progress:JSON.parse(localStorage.getItem('pm-progress')||'{}'),notes:JSON.parse(localStorage.getItem('pm-notes')||'{}')};

const meta=[
[1,25,'A. Comptabilité générale','1° Généralités'],[26,55,'A. Comptabilité générale','2° Tenue, structure et fonctionnement des comptes'],
[56,123,'A. Comptabilité générale',"3° Activité de l'entreprise"],[124,157,'A. Comptabilité générale','4° Investissements'],
[158,193,'A. Comptabilité générale',"5° Travaux d'inventaire"],[194,210,'A. Comptabilité générale','6° Opérations spécifiques'],
[211,226,'B. Comptabilité de gestion','1° Charges fixes et variables'],[227,234,'B. Comptabilité de gestion','2° Seuil de rentabilité'],
[235,247,'B. Comptabilité de gestion','3° Typologie des coûts'],[248,263,'C. Analyse financière','1° SIG, CAF et ratios de gestion'],
[264,276,'C. Analyse financière','2° Bilan fonctionnel et équilibres financiers'],[277,284,'C. Analyse financière','3° Ratios'],
[285,291,'C. Analyse financière','4° Tableaux de flux de trésorerie'],[292,295,'C. Analyse financière','5° Plan de financement'],
[296,300,'C. Analyse financière','6° Plan de trésorerie']];

const roomSpecs=[
{n:1,name:'Entrée',floor:'Rez-de-chaussée',icon:'🚪',range:[1,10],objects:[['Porte d’entrée','🚪'],['Paillasson','🧶'],['Porte-manteau','🧥'],['Miroir','🪞'],['Console','🗄️'],['Vase','🏺'],['Parapluies','☂️'],['Banc','🪑'],['Lampe','💡'],['Escalier','🪜']]},
{n:2,name:'Salon',floor:'Rez-de-chaussée',icon:'🛋️',range:[11,20],objects:[['Canapé','🛋️'],['Fauteuil','🪑'],['Table basse','🟫'],['Télévision','📺'],['Bibliothèque','📚'],['Lampadaire','💡'],['Tapis','🧶'],['Fenêtre','🪟'],['Plante','🪴'],['Cheminée','🔥']]},
{n:3,name:'Cuisine',floor:'Rez-de-chaussée',icon:'🍳',range:[21,30],objects:[['Réfrigérateur','🧊'],['Four','♨️'],['Évier','🚰'],['Plan de travail','🔪'],['Table','🍽️'],['Machine à café','☕'],['Placard','🗄️'],['Corbeille à fruits','🍎'],['Hotte','💨'],['Fenêtre','🪟']]},
{n:4,name:'Salle à manger',floor:'Rez-de-chaussée',icon:'🍽️',range:[31,40],objects:[['Grande table','🍽️'],['Chaise rouge','🪑'],['Chaise bleue','🪑'],['Buffet','🗄️'],['Lustre','💡'],['Vaisselier','🥂'],['Horloge','🕰️'],['Tableau','🖼️'],['Fenêtre','🪟'],['Tapis','🧶']]},
{n:5,name:'Bureau',floor:'Rez-de-chaussée',icon:'💻',range:[41,50],objects:[['Bureau','🖥️'],['Chaise','🪑'],['Ordinateur','💻'],['Imprimante','🖨️'],['Lampe','💡'],['Étagère','📚'],['Classeur','🗂️'],['Corbeille','🗑️'],['Fenêtre','🪟'],['Globe','🌍']]},
{n:6,name:'Bibliothèque',floor:'Rez-de-chaussée',icon:'📚',range:[51,60],objects:[['Grande étagère','📚'],['Fauteuil','🪑'],['Escabeau','🪜'],['Livre rouge','📕'],['Livre bleu','📘'],['Petit bureau','✍️'],['Lampe verte','💡'],['Globe','🌍'],['Statue','🗿'],['Fenêtre','🪟']]},
{n:7,name:'Véranda',floor:'Rez-de-chaussée',icon:'🌿',range:[61,70],objects:[['Baie vitrée','🪟'],['Fauteuil rotin','🪑'],['Table ronde','🟤'],['Plante haute','🌴'],['Ficus','🪴'],['Arrosoir','🚿'],['Hamac','🛏️'],['Lanterne','🏮'],['Tapis','🧶'],['Porte du jardin','🚪']]},
{n:8,name:'Buanderie',floor:'Rez-de-chaussée',icon:'🧺',range:[71,80],objects:[['Machine à laver','🧺'],['Sèche-linge','🌬️'],['Panier à linge','🧺'],['Évier','🚰'],['Étagère','🧴'],['Fer à repasser','♨️'],['Table à repasser','▬'],['Produits','🧴'],['Porte','🚪'],['Fenêtre','🪟']]},
{n:9,name:'Garage',floor:'Rez-de-chaussée',icon:'🚗',range:[81,90],objects:[['Voiture','🚗'],['Vélo','🚲'],['Établi','🧰'],['Caisse à outils','🧰'],['Étagère','📦'],['Pneu','🛞'],['Porte garage','🚪'],['Casier','🗄️'],['Pompe','⛽'],['Escabeau','🪜']]},
{n:10,name:'Atelier',floor:'Rez-de-chaussée',icon:'🔨',range:[91,100],objects:[['Établi','🪚'],['Marteau','🔨'],['Perceuse','🛠️'],['Étau','🗜️'],['Boîte de vis','🔩'],['Planche','🪵'],['Armoire','🗄️'],['Lampe','💡'],['Tabouret','🪑'],['Fenêtre','🪟']]},
{n:11,name:'Palier',floor:'Étage',icon:'🪜',range:[101,110],objects:[['Escalier','🪜'],['Rampe','〰️'],['Tableau','🖼️'],['Console','🗄️'],['Vase','🏺'],['Banc','🪑'],['Lampe','💡'],['Tapis','🧶'],['Fenêtre','🪟'],['Porte','🚪']]},
{n:12,name:'Chambre bleue',floor:'Étage',icon:'🛏️',range:[111,120],objects:[['Lit','🛏️'],['Oreiller','🛌'],['Table de nuit','🗄️'],['Lampe','💡'],['Armoire','🚪'],['Bureau','✍️'],['Chaise','🪑'],['Tapis','🧶'],['Fenêtre','🪟'],['Réveil','⏰']]},
{n:13,name:'Chambre verte',floor:'Étage',icon:'🪴',range:[121,130],objects:[['Lit vert','🛏️'],['Coussin','🟩'],['Commode','🗄️'],['Plante','🪴'],['Lampe','💡'],['Bibliothèque','📚'],['Fauteuil','🪑'],['Miroir','🪞'],['Fenêtre','🪟'],['Panier','🧺']]},
{n:14,name:'Chambre dorée',floor:'Étage',icon:'✨',range:[131,140],objects:[['Lit doré','🛏️'],['Coffre','🧰'],['Miroir','🪞'],['Commode','🗄️'],['Lampe','💡'],['Rideaux','🪟'],['Fauteuil','🪑'],['Tapis','🧶'],['Tableau','🖼️'],['Bougie','🕯️']]},
{n:15,name:'Dressing',floor:'Étage',icon:'👗',range:[141,150],objects:[['Armoire gauche','👗'],['Armoire droite','👔'],['Miroir','🪞'],['Penderie','🧥'],['Étagère chaussures','👟'],['Coffre à bijoux','💍'],['Pouf','🪑'],['Tiroirs','🗄️'],['Panier','🧺'],['Lampe','💡']]},
{n:16,name:'Salle de bain',floor:'Étage',icon:'🛁',range:[151,160],objects:[['Baignoire','🛁'],['Douche','🚿'],['Lavabo','🚰'],['Miroir','🪞'],['Serviettes','🧻'],['Panier','🧺'],['Armoire','🗄️'],['Tapis','🧶'],['Fenêtre','🪟'],['Plante','🪴']]},
{n:17,name:'Salle de jeux',floor:'Étage',icon:'🎲',range:[161,170],objects:[['Table de jeu','🎲'],['Coffre à jouets','🧸'],['Baby-foot','⚽'],['Console','🎮'],['Pouf','🪑'],['Étagère','🧩'],['Tapis','🧶'],['Fléchettes','🎯'],['Fenêtre','🪟'],['Lampe','💡']]},
{n:18,name:'Chambre d’amis',floor:'Étage',icon:'🛌',range:[171,180],objects:[['Lit','🛏️'],['Valise','🧳'],['Table de nuit','🗄️'],['Lampe','💡'],['Armoire','🚪'],['Chaise','🪑'],['Tableau','🖼️'],['Tapis','🧶'],['Fenêtre','🪟'],['Réveil','⏰']]},
{n:19,name:'Couloir',floor:'Étage',icon:'🚪',range:[181,190],objects:[['Porte 1','🚪'],['Porte 2','🚪'],['Console','🗄️'],['Miroir','🪞'],['Tableau','🖼️'],['Plante','🪴'],['Tapis long','🧶'],['Applique','💡'],['Fenêtre','🪟'],['Statue','🗿']]},
{n:20,name:'Grenier',floor:'Étage',icon:'📦',range:[191,200],objects:[['Malle','🧳'],['Cartons','📦'],['Vieille horloge','🕰️'],['Mannequin','🧍'],['Lampe','🏮'],['Échelle','🪜'],['Fauteuil','🪑'],['Cadre ancien','🖼️'],['Fenêtre ronde','🪟'],['Coffre','🧰']]},
{n:21,name:'Terrasse',floor:'Jardin & dépendances',icon:'☀️',range:[201,210],objects:[['Table extérieure','🍽️'],['Chaise longue','🪑'],['Parasol','⛱️'],['Barbecue','🔥'],['Pot de fleurs','🌺'],['Lanterne','🏮'],['Banc','🪑'],['Arrosoir','🚿'],['Porte-fenêtre','🪟'],['Escalier jardin','🪜']]},
{n:22,name:'Potager',floor:'Jardin & dépendances',icon:'🥕',range:[211,220],objects:[['Carré de tomates','🍅'],['Carottes','🥕'],['Salades','🥬'],['Brouette','🛒'],['Arrosoir','🚿'],['Râteau','🧹'],['Pelle','🪏'],['Compost','🪱'],['Épouvantail','🧍'],['Portillon','🚪']]},
{n:23,name:'Roseraie',floor:'Jardin & dépendances',icon:'🌹',range:[221,230],objects:[['Rosier rouge','🌹'],['Rosier blanc','🤍'],['Arche','🌿'],['Banc','🪑'],['Statue','🗿'],['Fontaine basse','⛲'],['Lanterne','🏮'],['Allée','🪨'],['Arrosoir','🚿'],['Portillon','🚪']]},
{n:24,name:'Piscine',floor:'Jardin & dépendances',icon:'🏊',range:[231,240],objects:[['Bassin','🏊'],['Plongeoir','🤿'],['Bouée','🛟'],['Transat','🪑'],['Parasol','⛱️'],['Douche','🚿'],['Échelle','🪜'],['Ballon','🏐'],['Serviette','🧻'],['Pool-house','🏠']]},
{n:25,name:'Pergola',floor:'Jardin & dépendances',icon:'🌿',range:[241,250],objects:[['Poteau gauche','🪵'],['Poteau droit','🪵'],['Table','🍽️'],['Banquette','🪑'],['Vigne','🍇'],['Guirlande','💡'],['Pot','🏺'],['Rideau','🧵'],['Tapis','🧶'],['Marche','🪨']]},
{n:26,name:'Serre',floor:'Jardin & dépendances',icon:'🌱',range:[251,260],objects:[['Porte vitrée','🚪'],['Table semis','🌱'],['Citronnier','🍋'],['Tomates','🍅'],['Arrosoir','🚿'],['Étagère','🪴'],['Terreau','🪴'],['Thermomètre','🌡️'],['Banc','🪑'],['Fenêtre toit','🪟']]},
{n:27,name:'Fontaine',floor:'Jardin & dépendances',icon:'⛲',range:[261,270],objects:[['Grande fontaine','⛲'],['Statue','🗿'],['Bassin rond','💧'],['Pont','🌉'],['Nénuphars','🪷'],['Banc','🪑'],['Lanterne','🏮'],['Pierre blanche','🪨'],['Arbre','🌳'],['Allée','🪨']]},
{n:28,name:'Cabane',floor:'Jardin & dépendances',icon:'🛖',range:[271,280],objects:[['Porte','🚪'],['Établi','🧰'],['Râteau','🧹'],['Pelle','🪏'],['Tondeuse','🌱'],['Étagère','📦'],['Bottes','🥾'],['Arrosoir','🚿'],['Fenêtre','🪟'],['Toit','🏠']]},
{n:29,name:'Verger',floor:'Jardin & dépendances',icon:'🍎',range:[281,290],objects:[['Pommier','🍎'],['Poirier','🍐'],['Cerisier','🍒'],['Échelle','🪜'],['Panier','🧺'],['Brouette','🛒'],['Ruche','🐝'],['Banc','🪑'],['Pierre','🪨'],['Portail','🚪']]},
{n:30,name:'Pavillon',floor:'Jardin & dépendances',icon:'🏡',range:[291,300],objects:[['Porte','🚪'],['Petit canapé','🛋️'],['Table','🟫'],['Bibliothèque','📚'],['Lampe','💡'],['Coffre','🧰'],['Fenêtre','🪟'],['Tapis','🧶'],['Plante','🪴'],['Cloche','🔔']]}
];
const locusPositions=[[9,13],[37,9],[72,13],[15,36],[44,34],[75,37],[9,68],[36,69],[65,68],[84,66]];

function roomForId(id){return roomSpecs.find(r=>id>=r.range[0]&&id<=r.range[1])}
function hydrate(row){let [id,term,definition,_oldRoom,_oldLocus,emoji,mnemonic,link]=row,m=meta.find(x=>id>=x[0]&&id<=x[1]),r=roomForId(id),idx=id-r.range[0],obj=r.objects[idx];return{id,term,definition,emoji,mnemonic,link,part:m[2],subsection:m[3],room:r.name,floor:r.floor,roomNo:r.n,locus:obj[0],locusIcon:obj[1],x:locusPositions[idx][0],y:locusPositions[idx][1]}}
function save(){localStorage.setItem('pm-progress',JSON.stringify(state.progress));localStorage.setItem('pm-notes',JSON.stringify(state.notes))}
function pg(id){return state.progress[id]||{status:'new',next:0,good:0,bad:0}}
function due(n){let x=pg(n.id);return x.status!=='mastered'||!x.next||x.next<=Date.now()}
function rate(id,status){let x={...pg(id),status};if(status==='mastered'){x.good=(x.good||0)+1;x.next=Date.now()+604800000}else if(status==='fragile'){x.bad=(x.bad||0)+1;x.next=Date.now()+86400000}else{x.bad=(x.bad||0)+1;x.next=Date.now()+1200000}state.progress[id]=x;save();render()}
function speak(text,r=1){if(!('speechSynthesis'in window))return; speechSynthesis.cancel();let u=new SpeechSynthesisUtterance(text);u.lang='fr-FR';u.rate=r;speechSynthesis.speak(u)}
function status(id){let s=pg(id).status;return s==='mastered'?'🟢 maîtrisée':s==='fragile'?'🟠 fragile':s==='learning'?'🔴 à apprendre':'⚪ nouvelle'}
function statusClass(id){return pg(id).status||'new'}
function top(content){return `<div class="shell"><header class="topbar"><div class="brand">Palais mental<small>Maison fixe · 300 loci</small></div><div class="search"><span>⌕</span><input id="q" placeholder="Chercher une notion…"></div><nav class="nav"><button data-v="house">Maison</button><button data-v="review">Réviser</button><button data-v="list">Notions</button></nav></header><div id="results"></div>${content}</div>`}
function progressSummary(){let m=state.notions.filter(n=>pg(n.id).status==='mastered').length,f=state.notions.filter(n=>pg(n.id).status==='fragile').length,d=state.notions.filter(due).length;return{m,f,d}}
function floorTabs(){return `<div class="floor-tabs">${['Rez-de-chaussée','Étage','Jardin & dépendances'].map(f=>`<button class="${state.floor===f?'active':''}" data-floor="${f}">${f==='Rez-de-chaussée'?'🏠':f==='Étage'?'🪜':'🌳'} ${f}</button>`).join('')}</div>`}
function house(){let {m,f,d}=progressSummary(),rooms=roomSpecs.filter(r=>r.floor===state.floor);return top(`<section class="house-hero"><div><div class="eyebrow">Vrai palais mental spatial</div><h1>Ta maison mentale</h1><p class="lead">Chaque pièce est fixe. Chaque objet est fixe. Chaque objet correspond à une seule notion, toujours au même endroit.</p></div><div class="mini-stats"><b>${m}/300</b><span>maîtrisées</span><small>${f} fragiles · ${d} à revoir</small></div></section>${floorTabs()}<section class="house-plan" aria-label="Plan de la maison">${rooms.map(r=>{let ns=state.notions.filter(n=>n.room===r.name),mastered=ns.filter(n=>pg(n.id).status==='mastered').length;return `<button class="plan-room room-${r.n}" data-room="${esc(r.name)}"><span class="room-order">${r.n}</span><span class="room-icon">${r.icon}</span><b>${esc(r.name)}</b><small>${r.range[0]}–${r.range[1]}</small><span class="room-progress"><i style="width:${mastered*10}%"></i></span></button>`}).join('')}<div class="plan-path">Parcours fixe → de la pièce ${rooms[0].n} à la pièce ${rooms.at(-1).n}</div></section><section class="memory-rule"><b>Règle du palais :</b> ne cherche pas d’abord le mot. Regarde mentalement la pièce, retrouve l’objet, puis laisse l’association te ramener au terme.</section>`)}
function roomView(){let r=roomSpecs.find(x=>x.name===state.room);if(!r)return house();let ns=state.notions.filter(n=>n.room===r.name);return top(`<div class="breadcrumbs"><button data-back-house>← Plan de ${esc(r.floor)}</button><span class="pill">Pièce ${r.n}/30</span><span class="pill">Notions ${r.range[0]}–${r.range[1]}</span></div><div class="section-title"><div><div class="eyebrow">${esc(r.floor)}</div><h2>${r.icon} ${esc(r.name)}</h2><p class="muted">Clique sur un objet. Le nom de la notion reste caché jusqu’à l’ouverture de la fiche.</p></div><button class="secondary" data-walk-room>▶ Réviser cette pièce</button></div><section class="room-scene theme-${r.n%6}"><div class="wall wall-top"></div><div class="wall wall-left"></div><div class="wall wall-right"></div><div class="wall wall-bottom"></div><div class="room-name-plate">${esc(r.name)}</div>${ns.map(n=>`<button class="furniture ${statusClass(n.id)} ${state.highlight===n.id?'highlight':''}" style="left:${n.x}%;top:${n.y}%" data-n="${n.id}" aria-label="${esc(n.locus)}"><span class="furniture-icon">${n.locusIcon}</span><span class="furniture-label">${esc(n.locus)}</span><span class="notion-pin">${n.id}</span></button>`).join('')}<div class="walk-arrow a1">➜</div><div class="walk-arrow a2">➜</div><div class="walk-arrow a3">➜</div></section><div class="room-legend"><span>⚪ nouvelle</span><span>🔴 à apprendre</span><span>🟠 fragile</span><span>🟢 maîtrisée</span></div>`)}
function review(){let pool=state.room?state.notions.filter(n=>n.room===state.room):state.notions.filter(due);if(!pool.length)pool=state.notions;let n=state.current&&pool.some(x=>x.id===state.current.id)?state.current:pool[Math.floor(Math.random()*pool.length)];state.current=n;return top(`<section class="practice"><div class="section-title"><div><div class="eyebrow">Révision palais mental</div><h2>Lieu → objet → mot</h2></div><span class="pill">${status(n.id)}</span></div><article class="card question-card"><div class="location-card"><span>${n.floor==='Jardin & dépendances'?'🌳':'🏠'}</span><div><b>${esc(n.room)}</b><small>Objet : ${esc(n.locus)}</small></div></div><div class="review-object">${n.locusIcon}</div><h3>Quelle notion as-tu placée sur cet objet ?</h3><p class="muted">Essaie d’abord sans regarder l’association.</p><button class="primary" data-reveal>Voir l’association et la réponse</button><div id="reveal" class="hidden reveal"><div class="mnemonic-stage"><span class="visual">${n.emoji}</span><h3>${esc(n.mnemonic)}</h3><p>${esc(n.link)}</p></div><h2>${esc(n.term)}</h2><div class="definition">${esc(n.definition)}</div><div class="actions" style="justify-content:center"><button class="secondary" data-say>🔊 Lire</button><button class="secondary" data-mic>🎤 Dicter ma définition</button></div><textarea id="answer" class="answer" placeholder="Écris ou dicte ta définition…"></textarea><div class="status-row"><button class="status-btn red" data-rate="learning">Je ne savais pas</button><button class="status-btn orange" data-rate="fragile">Fragile</button><button class="status-btn green" data-rate="mastered">Je maîtrise</button></div></div></article><div class="actions" style="justify-content:center"><button class="secondary" data-go-locus>📍 Voir dans la pièce</button><button class="secondary" data-next>Notion suivante →</button></div></section>`)}
function listView(){return top(`<div class="section-title"><div><div class="eyebrow">Index du palais</div><h2>Les 300 notions et leur emplacement</h2></div></div><section class="notion-list">${state.notions.map(n=>`<button data-jump="${n.id}"><span class="num">${n.id}</span><span><b>${esc(n.term)}</b><small>${esc(n.room)} → ${esc(n.locus)}</small></span><span>${status(n.id).split(' ')[0]}</span></button>`).join('')}</section>`)}
function modal(n){let el=document.createElement('div');el.className='modal-backdrop';el.innerHTML=`<div class="modal"><div class="modal-head"><div><span class="pill">#${n.id} · ${status(n.id)}</span><h2>${esc(n.term)}</h2><div class="location">📍 ${esc(n.floor)} → ${esc(n.room)} → <b>${esc(n.locus)}</b></div></div><button class="icon-btn" data-close>✕</button></div><div class="locus-reminder"><span>${n.locusIcon}</span><div><small>OBJET-LOCUS</small><b>${esc(n.locus)}</b></div></div><div class="mnemonic-stage"><span class="visual">${n.emoji}</span><h3>${esc(n.mnemonic)}</h3><p class="muted"><b>Lien :</b> ${esc(n.link)}</p></div><div class="course-tag">${esc(n.part)} · ${esc(n.subsection)}</div><h3>Définition</h3><div class="definition">${esc(n.definition)}</div><div class="actions"><button class="primary" data-say>🔊 Lire mot + définition</button><button class="secondary" data-room-jump>📍 Revoir l’objet</button></div><h3 style="margin-top:20px">Ma restitution / note</h3><textarea class="note" placeholder="Écris ici la définition de mémoire ou une note personnelle…">${esc(state.notes[n.id]||'')}</textarea><div class="status-row"><button class="status-btn red" data-rate="learning">🔴 À apprendre</button><button class="status-btn orange" data-rate="fragile">🟠 Fragile</button><button class="status-btn green" data-rate="mastered">🟢 Maîtrisée</button></div></div>`;document.body.appendChild(el);$('[data-close]',el).onclick=()=>el.remove();$('[data-say]',el).onclick=()=>speak(`${n.term}. ${n.definition}`);$('.note',el).oninput=e=>{state.notes[n.id]=e.target.value;save()};$('[data-room-jump]',el).onclick=()=>{el.remove();gotoLocus(n)};$$('[data-rate]',el).forEach(b=>b.onclick=()=>{rate(n.id,b.dataset.rate);el.remove()});el.onclick=e=>{if(e.target===el)el.remove()}}
function gotoLocus(n){state.view='room';state.floor=n.floor;state.room=n.room;state.highlight=n.id;render();setTimeout(()=>{document.querySelector(`[data-n="${n.id}"]`)?.scrollIntoView({behavior:'smooth',block:'center'})},80)}
function search(q){let box=$('#results');if(!q.trim()){box.innerHTML='';return}let s=q.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,''),r=state.notions.filter(n=>(n.term+' '+n.definition+' '+n.room+' '+n.locus).toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').includes(s)).slice(0,10);box.innerHTML=`<div class="search-results">${r.map(n=>`<button class="search-result" data-search-jump="${n.id}"><b>#${n.id} ${esc(n.term)}</b><small>${esc(n.room)} → ${esc(n.locus)}</small></button>`).join('')}</div>`;$$('[data-search-jump]').forEach(x=>x.onclick=()=>{box.innerHTML='';gotoLocus(state.notions.find(n=>n.id==x.dataset.searchJump))})}
function mic(){const R=window.SpeechRecognition||window.webkitSpeechRecognition;if(!R)return alert("La dictée vocale n'est pas disponible dans ce navigateur.");let r=new R();r.lang='fr-FR';r.onresult=e=>{$('#answer').value=e.results[0][0].transcript};r.start()}
function bind(){$$('[data-v]').forEach(b=>b.onclick=()=>{state.view=b.dataset.v;state.room=null;state.current=null;state.highlight=null;render()});$$('[data-floor]').forEach(b=>b.onclick=()=>{state.floor=b.dataset.floor;state.room=null;state.view='house';render()});$$('[data-room]').forEach(b=>b.onclick=()=>{state.room=b.dataset.room;state.view='room';state.highlight=null;render()});$$('[data-n]').forEach(b=>b.onclick=()=>modal(state.notions.find(n=>n.id==b.dataset.n)));$$('[data-jump]').forEach(b=>b.onclick=()=>gotoLocus(state.notions.find(n=>n.id==b.dataset.jump)));$('[data-back-house]')&&($('[data-back-house]').onclick=()=>{state.view='house';state.room=null;state.highlight=null;render()});$('[data-walk-room]')&&($('[data-walk-room]').onclick=()=>{state.view='review';state.current=null;render()});$('[data-reveal]')&&($('[data-reveal]').onclick=()=>$('#reveal').classList.remove('hidden'));$('[data-next]')&&($('[data-next]').onclick=()=>{state.current=null;render()});$('[data-go-locus]')&&($('[data-go-locus]').onclick=()=>gotoLocus(state.current));$('[data-say]')&&($('[data-say]').onclick=()=>speak(`${state.current.term}. ${state.current.definition}`));$('[data-mic]')&&($('[data-mic]').onclick=mic);$$('[data-rate]').forEach(b=>b.onclick=()=>rate(state.current.id,b.dataset.rate));$('#q')&&($('#q').oninput=e=>search(e.target.value))}
function render(){document.querySelector('.modal-backdrop')?.remove();let content=state.view==='house'?house():state.view==='room'?roomView():state.view==='review'?review():listView();$('#app').innerHTML=content;bind()}
async function init(){let files=['001-050','051-100','101-150','151-200','201-250','251-300'];state.notions=(await Promise.all(files.map(f=>fetch(`./data/notions-${f}.json`).then(r=>{if(!r.ok)throw new Error(`Données introuvables: ${f}`);return r.json()})))).flat().map(hydrate);render();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{})}
init().catch(err=>{$('#app').innerHTML=`<div class="shell"><div class="card"><h2>Impossible de charger le palais</h2><p>${esc(err.message)}</p></div></div>`;console.error(err)});
