const $=(s,e=document)=>e.querySelector(s), $$=(s,e=document)=>[...e.querySelectorAll(s)];
const esc=s=>(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const state={notions:[],view:'home',zone:null,room:null,current:null,progress:JSON.parse(localStorage.getItem('pm-progress')||'{}'),notes:JSON.parse(localStorage.getItem('pm-notes')||'{}')};
const zones=[['Maison principale','🏠','Comptabilité générale'],['Jardin des coûts','🌿','Comptabilité de gestion'],['Château financier','🏰','Analyse financière']];
const meta=[
[1,25,'A. Comptabilité générale','1° Généralités','Maison principale'],[26,55,'A. Comptabilité générale','2° Tenue, structure et fonctionnement des comptes','Maison principale'],
[56,123,'A. Comptabilité générale',"3° Activité de l'entreprise",'Maison principale'],[124,157,'A. Comptabilité générale','4° Investissements','Maison principale'],
[158,193,'A. Comptabilité générale',"5° Travaux d'inventaire",'Maison principale'],[194,210,'A. Comptabilité générale','6° Opérations spécifiques','Maison principale'],
[211,226,'B. Comptabilité de gestion','1° Charges fixes et variables','Jardin des coûts'],[227,234,'B. Comptabilité de gestion','2° Seuil de rentabilité','Jardin des coûts'],
[235,247,'B. Comptabilité de gestion','3° Typologie des coûts','Jardin des coûts'],[248,263,'C. Analyse financière','1° SIG, CAF et ratios de gestion','Château financier'],
[264,276,'C. Analyse financière','2° Bilan fonctionnel et équilibres financiers','Château financier'],[277,284,'C. Analyse financière','3° Ratios','Château financier'],
[285,291,'C. Analyse financière','4° Tableaux de flux de trésorerie','Château financier'],[292,295,'C. Analyse financière','5° Plan de financement','Château financier'],
[296,300,'C. Analyse financière','6° Plan de trésorerie','Château financier']];
function hydrate(r){let [id,term,definition,room,locus,emoji,mnemonic,link]=r,m=meta.find(x=>id>=x[0]&&id<=x[1]);return{id,term,definition,room,locus,emoji,mnemonic,link,part:m[2],subsection:m[3],zone:m[4]}}
function save(){localStorage.setItem('pm-progress',JSON.stringify(state.progress));localStorage.setItem('pm-notes',JSON.stringify(state.notes))}
function pg(id){return state.progress[id]||{status:'new',next:0,good:0,bad:0}}
function due(n){let x=pg(n.id);return x.status!=='mastered'||!x.next||x.next<=Date.now()}
function rate(id,status){let x={...pg(id),status};if(status==='mastered'){x.good++;x.next=Date.now()+604800000}else if(status==='fragile'){x.bad++;x.next=Date.now()+86400000}else{x.bad++;x.next=Date.now()+1200000}state.progress[id]=x;save();render()}
function speak(text,r=1){if(!('speechSynthesis' in window))return; speechSynthesis.cancel();let u=new SpeechSynthesisUtterance(text);u.lang='fr-FR';u.rate=r;speechSynthesis.speak(u)}
function status(id){let s=pg(id).status;return s==='mastered'?'🟢 maîtrisée':s==='fragile'?'🟠 fragile':s==='learning'?'🔴 à apprendre':'⚪ nouvelle'}
function top(content){return `<div class="shell"><header class="topbar"><div class="brand">Palais mental<small>300 notions de comptabilité</small></div><div class="search"><span>⌕</span><input id="q" placeholder="Chercher une notion…"></div><nav class="nav"><button data-v="home">Accueil</button><button data-v="explore">Explorer</button><button data-v="review">Réviser</button><button data-v="gallery">Images</button></nav></header><div id="results"></div>${content}</div>`}
function home(){
 let m=state.notions.filter(n=>pg(n.id).status==='mastered').length,f=state.notions.filter(n=>pg(n.id).status==='fragile').length,d=state.notions.filter(due).length,p=Math.round(m/3);
 return top(`<section class="hero"><div class="hero-copy"><div class="eyebrow">Ton domaine mental fixe</div><h1>Entre. Regarde. Retrouve.</h1><p class="lead">Un lieu stable, une scène qui bouge, un mot, puis sa définition exacte. La maison se mémorise en même temps que le cours.</p><div class="actions"><button class="primary" data-v="review">🧠 Révision du jour · ${d}</button><button class="secondary" data-v="explore">🏰 Explorer</button></div></div><aside class="hero-card"><span class="pill">Progression</span><div class="big-progress">${m}<small style="font-size:1.2rem"> / 300</small></div><div class="progressbar"><i style="width:${p}%"></i></div><div class="stats"><div class="stat"><b>${m}</b><small>maîtrisées</small></div><div class="stat"><b>${f}</b><small>fragiles</small></div><div class="stat"><b>${d}</b><small>à revoir</small></div></div></aside></section><div class="section-title"><div><div class="eyebrow">Carte globale</div><h2>Trois territoires</h2></div></div><section class="domain">${zones.map(z=>`<button class="zone" data-zone="${z[0]}"><span class="emoji">${z[1]}</span><b>${z[0]}</b><p class="muted">${z[2]}</p></button>`).join('')}</section>`)
}
function explore(){
 if(!state.zone)return top(`<div class="section-title"><div><div class="eyebrow">Explorer</div><h2>Choisis un territoire</h2></div></div><section class="domain">${zones.map(z=>`<button class="zone" data-zone="${z[0]}"><span class="emoji">${z[1]}</span><b>${z[0]}</b><p class="muted">${z[2]}</p></button>`).join('')}</section>`);
 let ns=state.notions.filter(n=>n.zone===state.zone),rooms=[...new Set(ns.map(n=>n.room))];
 if(!state.room)return top(`<div class="breadcrumbs"><button data-back>← Domaines</button><span class="pill">${state.zone}</span></div><div class="section-title"><h2>${state.zone}</h2><span class="pill">${ns.length} loci</span></div><section class="grid">${rooms.map(r=>{let a=ns.filter(n=>n.room===r),m=a.filter(n=>pg(n.id).status==='mastered').length;return`<button class="card room-card" data-room="${esc(r)}" style="text-align:left;color:white"><span class="pill">${m}/${a.length}</span><h3>${esc(r)}</h3><p class="muted">${esc(a[0].subsection)}</p></button>`}).join('')}</section>`);
 ns=ns.filter(n=>n.room===state.room);
 return top(`<div class="breadcrumbs"><button data-back-room>← ${state.zone}</button><span class="pill">${esc(state.room)}</span></div><div class="section-title"><div><div class="eyebrow">${esc(ns[0]?.subsection)}</div><h2>${esc(state.room)}</h2></div></div><section class="loci">${ns.map(n=>`<button class="locus ${pg(n.id).status}" data-n="${n.id}"><span class="halo"></span><small>#${n.id} · ${esc(n.locus)}</small><span class="visual">${n.emoji}</span><b>${esc(n.term)}</b><small style="display:block;margin-top:8px">${status(n.id)}</small></button>`).join('')}</section>`)
}
function review(){
 let pool=state.notions.filter(due);if(!pool.length)pool=state.notions;let n=state.current||pool[Math.floor(Math.random()*pool.length)];state.current=n;
 return top(`<section class="practice"><div class="section-title"><div><div class="eyebrow">Révision espacée</div><h2>Lieu → mot → définition</h2></div><span class="pill">${status(n.id)}</span></div><article class="card question-card"><div class="pill">📍 ${esc(n.zone)} → ${esc(n.room)} → ${esc(n.locus)}</div><div class="visual">${n.emoji}</div><p class="muted">${esc(n.mnemonic)}</p><h3>Quelle notion se trouve ici ?</h3><button class="primary" data-reveal>Voir la réponse</button><div id="reveal" class="hidden reveal"><h2>${esc(n.term)}</h2><p class="location">${esc(n.link)}</p><div class="definition">${esc(n.definition)}</div><div class="actions" style="justify-content:center"><button class="secondary" data-say>🔊 Lire</button><button class="secondary" data-mic>🎤 Dicter ma définition</button></div><textarea id="answer" class="answer" placeholder="Écris ou dicte ta définition…"></textarea><div class="status-row"><button class="status-btn red" data-rate="learning">Je ne savais pas</button><button class="status-btn orange" data-rate="fragile">Fragile</button><button class="status-btn green" data-rate="mastered">Je maîtrise</button></div></div></article><div class="actions" style="justify-content:center"><button class="secondary" data-next>Notion suivante →</button></div></section>`)
}
function gallery(){let cards=state.notions.map(n=>`<button class="mnemo-card" data-n="${n.id}"><span class="mnemo-number">#${n.id}</span><span class="visual">${n.emoji}</span><b>${esc(n.term)}</b><small>${esc(n.link)}</small></button>`).join('');return top(`<div class="section-title"><div><div class="eyebrow">Mnémothèque</div><h2>300 scènes mnémotechniques</h2><p class="muted">Chaque scène est liée à un locus fixe. Clique sur une carte pour ouvrir le mot, la définition et ta note personnelle.</p></div></div><section class="mnemo-grid">${cards}</section>`)}
function modal(n){
 let el=document.createElement('div');el.className='modal-backdrop';el.innerHTML=`<div class="modal"><div class="modal-head"><div><span class="pill">#${n.id} · ${status(n.id)}</span><h2>${esc(n.term)}</h2><div class="location">📍 ${esc(n.zone)} → ${esc(n.room)} → ${esc(n.locus)}</div></div><button class="icon-btn" data-close>✕</button></div><div class="mnemonic-stage"><span class="visual">${n.emoji}</span><h3>${esc(n.mnemonic)}</h3><p class="muted">${esc(n.link)}</p></div><h3>Définition</h3><div class="definition">${esc(n.definition)}</div><div class="actions"><button class="primary" data-say>🔊 Lire mot + définition</button></div><h3 style="margin-top:20px">Ma note</h3><textarea class="note">${esc(state.notes[n.id]||'')}</textarea><div class="status-row"><button class="status-btn red" data-rate="learning">🔴 À apprendre</button><button class="status-btn orange" data-rate="fragile">🟠 Fragile</button><button class="status-btn green" data-rate="mastered">🟢 Maîtrisée</button></div></div>`;document.body.appendChild(el);
 $('[data-close]',el).onclick=()=>el.remove();$('[data-say]',el).onclick=()=>speak(`${n.term}. ${n.definition}`);$('.note',el).oninput=e=>{state.notes[n.id]=e.target.value;save()};$$('[data-rate]',el).forEach(b=>b.onclick=()=>{rate(n.id,b.dataset.rate);el.remove()});el.onclick=e=>{if(e.target===el)el.remove()}
}
function search(q){let b=$('#results');if(!q.trim()){b.innerHTML='';return}let s=q.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,''),r=state.notions.filter(n=>(n.term+' '+n.definition).toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').includes(s)).slice(0,10);b.innerHTML=`<div class="search-results">${r.map(n=>`<button class="search-result" data-s="${n.id}"><b>#${n.id} ${esc(n.term)}</b><small class="muted" style="display:block">${esc(n.room)}</small></button>`).join('')}</div>`;$$('[data-s]').forEach(x=>x.onclick=()=>{b.innerHTML='';modal(state.notions.find(n=>n.id==x.dataset.s))})}
function mic(){
 const R=window.SpeechRecognition||window.webkitSpeechRecognition;if(!R)return alert("La dictée vocale n'est pas disponible dans ce navigateur.");let r=new R();r.lang='fr-FR';r.onresult=e=>{$('#answer').value=e.results[0][0].transcript};r.start()
}
function bind(){
 $$('[data-v]').forEach(b=>b.onclick=()=>{state.view=b.dataset.v;state.current=null;render()});$$('[data-zone]').forEach(b=>b.onclick=()=>{state.view='explore';state.zone=b.dataset.zone;state.room=null;render()});$$('[data-room]').forEach(b=>b.onclick=()=>{state.room=b.dataset.room;render()});$$('[data-n]').forEach(b=>b.onclick=()=>modal(state.notions.find(n=>n.id==b.dataset.n)));$('[data-back]')&&($('[data-back]').onclick=()=>{state.zone=null;render()});$('[data-back-room]')&&($('[data-back-room]').onclick=()=>{state.room=null;render()});$('[data-reveal]')&&($('[data-reveal]').onclick=()=>$('#reveal').classList.remove('hidden'));$('[data-next]')&&($('[data-next]').onclick=()=>{state.current=null;render()});$('[data-say]')&&($('[data-say]').onclick=()=>speak(`${state.current.term}. ${state.current.definition}`));$('[data-mic]')&&($('[data-mic]').onclick=mic);$$('[data-rate]').forEach(b=>b.onclick=()=>rate(state.current.id,b.dataset.rate));$('#q').oninput=e=>search(e.target.value)
}
function render(){document.querySelector('.modal-backdrop')?.remove();$('#app').innerHTML=state.view==='home'?home():state.view==='explore'?explore():state.view==='review'?review():gallery();bind()}
async function init(){let files=['001-050','051-100','101-150','151-200','201-250','251-300'];state.notions=(await Promise.all(files.map(f=>fetch(`./data/notions-${f}.json`).then(r=>{if(!r.ok)throw new Error(`Données introuvables: ${f}`);return r.json()})))).flat().map(hydrate);render();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{})}
init().catch(err=>{document.querySelector('#app').innerHTML=`<div class="shell"><div class="card"><h2>Impossible de charger le palais</h2><p>${esc(err.message)}</p></div></div>`;console.error(err)});
